import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ro' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'ro';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, any>> = {
  ro: {
    nav: {
      about: 'Despre noi',
      portfolio: 'Portofoliu',
      services: 'Servicii',
      blog: 'Blog',
      shop: 'Shop',
      contact: 'Contact',
      callNow: 'Sună acum'
    },
    home: {
      heroTitle: 'Design Interior București',
      heroSubtitle: 'Transformăm spațiile în opere de artă prin eleganță, rafinament și atenție la detalii',
      heroCta: 'Programează o consultație gratuită',
      aboutTitle: 'Excelența în',
      aboutHighlight: 'Design Interior',
      aboutDescription: 'Cu peste 13 ani de experiență în crearea de spații exclusive, Jubilee Luxury Design îmbină artă, funcționalitate și eleganță pentru a realiza interioare care depășesc așteptările.',
      feature1: 'Design personalizat și exclusivist',
      feature2: 'Materiale premium și mobilier de lux',
      feature3: 'Servicii complete turnkey',
      readStory: 'Citește povestea noastră',
      projectsTitle: 'Proiecte',
      projectsHighlight: 'Exclusive',
      projectsDescription: 'Fiecare proiect este o poveste unică de eleganță și rafinament, creată special pentru clienții noștri exigenți',
      viewPortfolio: 'Vezi tot portofoliul',
      ctaTitle: 'Pregătit să îți transformi spațiul?',
      residential: 'Rezidențial',
      commercial: 'Comercial',
      penthouse: 'Penthouse Exclusivist',
      villa: 'Villa Contemporană',
      showroom: 'Showroom Premium',
      altBedroom: 'Design interior dormitor de lux',
      altKitchen: 'Design interior bucătărie de lux',
      altLiving: 'Design interior modern living de lux'
    },
    footer: {
      inspirationTitle: 'Inspirație &',
      inspirationHighlight: 'Tendințe',
      inspirationDescription: 'Primește lunar idei exclusive de design interior, tendințe și sfaturi de la experții Jubilee Luxury Design',
      emailPlaceholder: 'Adresa ta de email',
      subscribe: 'Abonează-te',
      brandDescription: 'De peste 13 ani, creăm spații exclusive care îmbină eleganța cu funcționalitatea, oferind servicii complete de design interior de lux pentru clienți exigenți.',
      services: 'Servicii',
      aboutUs: 'Despre noi',
      resources: 'Resurse',
      completeDesign: 'Design Interior Complet',
      designConsultancy: 'Consultanță Design',
      premiumFurniture: 'Mobilier Premium',
      commercialDesign: 'Design Comercial',
      ourStory: 'Povestea noastră',
      portfolio: 'Portofoliu',
      testimonials: 'Testimoniale',
      designBlog: 'Blog Design',
      styleGuide: 'Ghid Stiluri',
      allRights: 'Toate drepturile rezervate.',
      privacyPolicy: 'Politica de confidențialitate',
      termsConditions: 'Termeni și condiții',
      cookiesPolicy: 'Politica cookies',
      cookieSettings: 'Setări cookie-uri'
    },
    about: {
      heroTitle: 'Povestea',
      heroHighlight: 'Jubilee Luxury Design',
      heroDescription: 'De peste 13 ani, creăm spații exclusive care reflectă personalitatea și visurile clienților noștri',
      storyTitle: 'O Viziune Născută din Pasiune',
      storyP1: 'Jubilee Luxury Design s-a născut în 2012 dintr-o pasiune pentru frumusețe, funcționalitate și dorința de a transforma fiecare spațiu într-o operă de artă unică.',
      storyP2: 'Specializându-ne în design interior de lux, am dezvoltat o abordare holistică care îmbină eleganța atemporală cu inovația contemporană, creând interioare care depășesc tendințele momentului.',
      storyP3: 'Filozofia noastră se bazează pe ideea că fiecare client este unic, iar casa sa trebuie să reflecte personalitatea, stilul de viață și aspirațiile sale.',
      yearsExperience: 'Ani de experiență',
      completedProjects: 'Proiecte finalizate',
      happyClients: 'Clienți mulțumiți',
      teamDescription: 'Profesioniști cu experiență, dedicați excelenței în design',
      philosophyTitle: 'Filozofia Noastră',
      excellence: 'Excelență',
      excellenceDesc: 'Standardele noastre înalte se reflectă în fiecare detaliu al proiectelor',
      personalization: 'Personalizare',
      personalizationDesc: 'Fiecare proiect este unic, adaptat perfect nevoilor clientului',
      exclusivity: 'Exclusivitate',
      exclusivityDesc: 'Acces la mobilier premium și piese de artă exclusiviste',
      startProject: 'Începe proiectul tău'
    },
    services: {
      heroTitle: 'Servicii',
      heroHighlight: 'Premium',
      heroDescription: 'Experiența noastră începe acolo unde visul tău prinde formă. Fiecare proiect este tratat cu atenția și eleganța pe care le merită, prin pachete complete de servicii, gândite să te însoțească în fiecare etapă — de la primele schițe până la ultimul detaliu de decor.',
      heroDescription2: 'Totul este personalizat: ritmul tău, stilul tău, povestea ta. Rezultatul? Un spațiu care nu doar arată bine, ci te face să simți că ești acasă.',
      completeDesignTitle: 'Design Interior Complet',
      completeDesignDesc: 'Serviciul nostru premium pentru transformarea completă a spațiului, de la concept la cheie în mână.',
      consultancyTitle: 'Consultanță Design',
      consultancyDesc: 'Perfect pentru clienții care doresc să implementeze proiectul prin resurse proprii.',
      furnitureTitle: 'Achiziție Mobilier Premium',
      furnitureDesc: 'Serviciu exclusiv de achiziție mobilier și accesorii de lux de la partenerii noștri selectați.',
      mostPopular: 'Cel mai popular',
      requestQuote: 'Solicită ofertă',
      completeFeature1: 'Concept complet și randări 3D fotorealistice',
      completeFeature2: 'Supraveghere execuție de la A la Z',
      completeFeature3: 'Finisaje de lux și materiale premium',
      completeFeature4: 'Planuri tehnice detaliate',
      completeFeature5: 'Coordonare furnizori și meșteri',
      completeFeature6: 'Consultanță post-finalizare inclusă',
      consultancyFeature1: 'Analiză detaliată a spațiului',
      consultancyFeature2: 'Mood boards și concept vizual',
      consultancyFeature3: 'Ghid paletă cromatică personalizat',
      consultancyFeature4: 'Recomandări mobilier și decorațiuni',
      consultancyFeature5: 'Planuri de amenajare 2D',
      consultancyFeature6: 'Raport detaliat și lista de cumpărături',
      furnitureFeature1: 'Acces showroom-uri exclusive',
      furnitureFeature2: 'Design mobilier personalizat',
      furnitureFeature3: 'Branduri italiene și europene premium',
      furnitureFeature4: 'Coordonare livrare și instalare',
      furnitureFeature5: 'Consultanță selecție textile și accesorii',
      furnitureFeature6: 'Garanție extinsă pe toate produsele',
      processTitle: 'Procesul Nostru de',
      processHighlight: 'Lucru',
      processDescription: 'Un proces structurat și transparent pentru rezultate excepționale',
      step1Title: 'Consultația Inițială',
      step1Desc: 'Întâlnire la domiciliu pentru analiza spațiului și înțelegerea nevoilor tale',
      step2Title: 'Dezvoltarea Conceptului',
      step2Desc: 'Crearea conceptului de design și prezentarea propunerii detaliate',
      step3Title: 'Planificare Detaliată',
      step3Desc: 'Planuri tehnice, lista de materiale și cronograma de implementare',
      step4Title: 'Implementarea',
      step4Desc: 'Execuția proiectului cu supravegherea constantă a echipei noastre',
      duration: 'Durată',
      guaranteesTitle: 'Garanțiile',
      guaranteesHighlight: 'Noastre',
      qualityGuarantee: 'Garanția Calității',
      qualityDesc: 'Materiale premium certificate și manoperă de cea mai înaltă calitate, garantată',
      budgetGuarantee: 'Respectarea Bugetului',
      budgetDesc: 'Preț fix stabilit de la început, fără costuri ascunse sau suplimentare',
      deliveryGuarantee: 'Livrare la Timp',
      deliveryDesc: 'Respectarea programului stabilit sau compensare pentru întârzieri',
      ctaTitle: 'Pregătit să Începi Proiectul?',
      ctaDescription: 'Consultația inițială este gratuită și fără obligații. Descoperă cum putem transforma spațiul tău.',
      scheduleFree: 'Programează consultația gratuită',
      duration1: '2-3 ore',
      duration2: '1-2 săptămâni',
      duration3: '1 săptămână',
      duration4: '4-12 săptămâni'
    },
    portfolio: {
      heroTitle: 'Portofoliu Premium',
      heroDescription: 'Colecția noastră de proiecte exclusive care redefinesc standardele de eleganță și rafinament',
      all: 'Toate',
      residential: 'Rezidențial',
      commercial: 'Comercial',
      penthouse: 'Penthouse',
      villa: 'Villa',
      viewDetails: 'Vezi detalii',
      processTitle: 'Procesul Nostru',
      processDescription: 'Fiecare proiect urmează un proces riguros de la concept la finalizare',
      consultation: 'Consultația',
      consultationDesc: 'Analiză detaliată a nevoilor și visurilor tale',
      concept: 'Conceptul',
      conceptDesc: 'Dezvoltarea unei viziuni unice și personalizate',
      execution: 'Execuția',
      executionDesc: 'Implementare precisă cu materiale premium',
      finalization: 'Finalizarea',
      finalizationDesc: 'Predarea unui spațiu perfect și funcțional',
      startProject: 'Începe proiectul tău'
    },
    contact: {
      heroTitle: 'Să Începem',
      heroHighlight: 'Împreună',
      heroDescription: 'Consultația inițială este gratuită și fără obligații. Contactează-ne pentru a discuta despre visul tău',
      formTitle: 'Programează Consultația',
      formHighlight: 'Gratuită',
      fullName: 'Nume complet',
      namePlaceholder: 'Numele tău',
      email: 'Email',
      emailPlaceholder: 'email@exemplu.com',
      phone: 'Telefon',
      phonePlaceholder: '+40 732 456 789',
      projectType: 'Tip proiect',
      selectProject: 'Selectează tipul proiectului',
      projectDetails: 'Detalii despre proiect',
      detailsPlaceholder: 'Spune-ne mai multe despre viziunea ta...',
      scheduleCta: 'Programează Consultația Gratuită',
      nextSteps: 'Ce urmează după trimiterea formularului?',
      step1: 'Te contactăm în maxim 24 de ore',
      step2: 'Programăm consultația la momentul potrivit',
      step3: 'Primești o propunere personalizată',
      phoneTitle: 'Telefon',
      emailTitle: 'Email',
      officeTitle: 'Birou',
      scheduleTitle: 'Program',
      callNow: 'Sună acum',
      sendEmail: 'Trimite email',
      viewOnMap: 'Vezi pe hartă',
      scheduleVisit: 'Programează vizită',
      uniqueExperience: 'O Experiență Unică te Așteaptă',
      personalizedConsultancy: 'Consultanță personalizată',
      freeParking: 'Parcare gratuită disponibilă',
      scheduleOfficeVisit: 'Programează vizita la biroul nostru',
      openInMaps: 'Deschide în Google Maps',
      faqTitle: 'Întrebări',
      faqHighlight: 'Frecvente',
      faq1Q: 'Cât durează un proiect?',
      faq1A: 'Între 4-12 săptămâni, în funcție de complexitatea proiectului și suprafața spațiului.',
      faq2Q: 'Ce include serviciul de design?',
      faq2A: 'Serviciul nostru include concept, planuri tehnice, vizualizări 3D, coordonarea furnizorilor și supravegherea execuției.',
      faq3Q: 'Lucrați în toată țara?',
      faq3A: 'Da, acceptăm proiecte în întreaga țară pentru suprafețe de minimum 150mp.',
      faq4Q: 'Care este bugetul minim?',
      faq4A: 'Bugetul minim pentru un proiect complet este de 25.000€, inclusiv mobilier și execuție.',
      viewAllFaq: 'Vezi toate întrebările frecvente',
      successTitle: 'Mesaj trimis cu succes!',
      successDescription: 'Vă vom contacta în maxim 24 de ore pentru programarea consultației.',
      gdprConsent: 'Sunt de acord cu',
      gdprPrivacyLink: 'Politica de confidențialitate',
      gdprAnd: 'și',
      gdprTermsLink: 'Termenii și condițiile',
      gdprRequired: 'Trebuie să acceptați politica de confidențialitate pentru a trimite formularul.',
      errorTitle: 'Eroare la trimitere',
      errorDescription: 'Nu am putut trimite mesajul. Vă rugăm să ne contactați telefonic.',
      service1: 'Design Interior Complet',
      service2: 'Consultanță Design',
      service3: 'Renovare & Reamenajare',
      service4: 'Achiziție Mobilier Premium',
      service5: 'Design Comercial',
      service6: 'Altele'
    },
    blog: {
      heroTitle: 'Blog',
      heroHighlight: 'Design',
      heroDescription: 'Inspirație, sfaturi și tendințe în design interior de la experții Design Interior București',
      all: 'Toate',
      trends: 'Tendințe',
      tips: 'Sfaturi',
      design: 'Design',
      materials: 'Materiale',
      readMore: 'Citește mai mult',
      readTime: 'min citire',
      newsletterTitle: 'Rămâi la curent cu noutățile',
      newsletterDescription: 'Abonează-te la newsletter-ul nostru pentru a primi cele mai noi articole și sfaturi de design.',
      emailPlaceholder: 'Adresa ta de email',
      subscribe: 'Abonează-te'
    },
    shop: {
      heroTitle: 'Resurse premium pentru designeri și arhitecți',
      heroDescription: 'Template-uri, ebook-uri și fișiere CAD care îți optimizează timpul, îți clarifică procesul și îți ridică prezentările la nivel profesionist.',
      enterShop: '👉 Intră în Shop',
      categories: 'Categorii',
      allProducts: 'Toate produsele',
      ebooks: 'Ebook-uri',
      templates: 'Template-uri',
      cadFiles: 'Fișiere CAD',
      packages: 'Pachete complete',
      viewProduct: 'Vezi produsul',
      whyWorksTitle: 'De ce funcționează aceste resurse?',
      benefit1: 'Te ajută să economisești ore întregi în procesul de lucru',
      benefit2: 'Prezinți proiectele într-un mod profesionist și convingător',
      benefit3: 'Te ajută să-ți organizezi clar tot fluxul cu clientul',
      benefit4: 'Documente premium inspirate de studiouri internaționale',
      benefit5: 'Rezultate mai bune și o experiență premium pentru client',
      testimonial1: 'Documentele sunt superbe și intuitive. Mi-au schimbat complet modul în care prezint proiectele.',
      testimonial2: 'Am simțit imediat cum arată o agenție premium. Template-urile sunt aur.',
      ctaTitle: 'Găsește resursele care îți eficientizează munca',
      ctaDescription: 'Documente premium pentru arhitecți și designeri care vor mai mult: ordine, profesionalism, eficiență.',
      buyNow: '👉 Cumpără acum',
      comingSoon: 'În curând',
      backToShop: 'Înapoi la Shop',
      buyProduct: 'Cumpără',
      whatIsIncluded: 'Ce include',
      securePayment: 'Plată securizată prin Stripe',
      instantDelivery: 'Livrare instant după plată',
      relatedProducts: 'Produse similare'
    },
    products: {
      starterPack: {
        title: 'Starter Pack Client',
        description: 'Set profesional pentru prima interacțiune cu un client: ghiduri, chestionare și documente esențiale. Te ajută să creezi un proces clar, premium și coerent de la primul contact.',
        longDescription: 'Starter Pack Client este resursa ideală pentru designeri și arhitecți care vor să facă o primă impresie impecabilă. Pachetul conține toate documentele necesare pentru a gestiona profesionist prima întâlnire cu clientul: de la chestionare detaliate la ghiduri de comunicare și șabloane de organizare. Fiecare element a fost creat pentru a te ajuta să economisești timp și să transmiți încredere din primul moment.',
        feature1: 'Chestionar detaliat pentru prima întâlnire',
        feature2: 'Ghid de comunicare profesională cu clientul',
        feature3: 'Șabloane de organizare a proiectului',
        feature4: 'Checklist pentru procesul de onboarding'
      },
      bathroomComplete: {
        title: 'Bathroom eBook + CAD Files + Template',
        description: 'Pachet complet pentru proiectarea băilor: ebook detaliat, fișiere CAD + template profesional. Tot ce ai nevoie pentru proiecte tehnic corecte și estetic impecabile.',
        longDescription: 'Acest pachet all-in-one îți oferă tot ce ai nevoie pentru proiecte de băi impecabile. Ebook-ul acoperă detalii tehnice esențiale, dimensiuni standard și soluții de layout, fișierele CAD sunt gata de utilizat în proiectele tale, iar template-ul profesional îți permite să prezinți clientului un concept coerent și convingător.',
        feature1: 'Ebook detaliat cu dimensiuni și layout-uri pentru băi',
        feature2: 'Fișiere CAD editabile și organizate',
        feature3: 'Template profesional pentru prezentări',
        feature4: 'Exemple de proiecte finalizate'
      },
      beigeContract: {
        title: 'BEIGE – Template Contract & Ofertă de Preț',
        description: 'Document elegant și ușor de personalizat pentru contracte și oferte. Construit pentru a transmite profesionalism și consecvență în relația cu clientul.',
        longDescription: 'Template-ul BEIGE este soluția perfectă pentru designeri care vor documente profesioniste fără efort. Creat cu atenție la detalii tipografice și vizuale, acest template îți permite să generezi rapid contracte și oferte de preț care inspiră încredere. Design-ul elegant și neutru se potrivește oricărui brand de design interior.',
        feature1: 'Template contract complet și personalizabil',
        feature2: 'Ofertă de preț cu design premium',
        feature3: 'Format ușor de editat și adaptat',
        feature4: 'Design elegant, potrivit pentru orice brand'
      },
      greenPresentation: {
        title: 'GREEN – Template Prezentare Companie',
        description: 'Template minimalist, perfect pentru pitch-uri, colaborări B2B, întâlniri corporate și prezentarea agenției tale.',
        longDescription: 'Template-ul GREEN este creat pentru a prezenta agenția ta de design într-un mod profesionist și memorabil. Cu un design minimalist și modern, este perfect pentru pitch-uri, întâlniri B2B și prezentări corporate. Slide-urile sunt organizate strategic pentru a comunica eficient povestea, serviciile și portofoliul tău.',
        feature1: 'Prezentare companie cu design minimalist',
        feature2: 'Slide-uri strategice pentru pitch-uri',
        feature3: 'Secțiuni pentru portofoliu și servicii',
        feature4: 'Ușor de personalizat cu brandul tău'
      },
      kitchenEbook: {
        title: 'Kitchen eBook + CAD Files',
        description: 'Ghid complet pentru proiectarea bucătăriilor + fișiere CAD organizate. Ideal pentru proiecte rapide, corecte și super profesionale.',
        longDescription: 'Ebook-ul de bucătărie este o resursă esențială pentru orice designer de interior. Acoperă tot ce trebuie să știi despre proiectarea bucătăriilor: de la ergonomie și dimensiuni standard, la tipuri de layout-uri și soluții de depozitare. Fișierele CAD incluse sunt organizate pe categorii și gata de integrat în proiectele tale.',
        feature1: 'Ghid complet de ergonomie pentru bucătării',
        feature2: 'Fișiere CAD organizate pe categorii',
        feature3: 'Tipuri de layout-uri și dimensiuni standard',
        feature4: 'Soluții de depozitare și optimizare a spațiului'
      },
      bathroomV2: {
        title: 'Bathroom eBook + CAD Files + Template (V2)',
        description: 'Pachet complet alternativ pentru proiecte de băi: detalii tehnice, fișiere CAD + template premium pentru prezentări.',
        longDescription: 'Versiunea V2 a pachetului de băi aduce un design actualizat și conținut extins. Include un ebook revizuit cu cele mai noi tendințe, fișiere CAD actualizate și un template premium cu un look fresh. Ideal pentru designeri care vor să rămână la curent cu evoluțiile din industrie.',
        feature1: 'Ebook revizuit cu tendințe actuale',
        feature2: 'Fișiere CAD actualizate și extinse',
        feature3: 'Template premium cu design fresh',
        feature4: 'Conținut extins față de versiunea anterioară'
      },
      millworkGuide: {
        title: 'Millwork – Ghid complet pentru mobilier custom',
        description: 'Ghid premium cu dimensiuni standard, detalii tehnice, exemple concrete pentru bucătării, dressing-uri, biblioteci. Resursa perfectă pentru un flux de lucru mai rapid, mai coerent și mai sigur — fără erori, fără improvizații.',
        longDescription: 'Ghidul Millwork este resursa definitivă pentru designeri care lucrează cu mobilier custom. Acoperă în detaliu dimensiuni standard, toleranțe, tipuri de îmbinări și materiale pentru bucătării, dressing-uri, biblioteci și alte piese de mobilier. Cu exemple concrete și diagrame tehnice, acest ghid elimină incertitudinea și reduce erorile din procesul de proiectare.',
        feature1: 'Dimensiuni standard pentru toate tipurile de mobilier',
        feature2: 'Detalii tehnice pentru bucătării și dressing-uri',
        feature3: 'Exemple concrete și diagrame tehnice',
        feature4: 'Ghid de materiale și tipuri de îmbinări'
      }
    },
    legal: {
      back: '← Înapoi'
    },
    seo: {
      homeTitle: 'Design Interior București',
      homeDesc: 'Studio de design interior de lux în București. Servicii complete de amenajare premium, consultanță design și mobilier exclusivist.',
      aboutTitle: 'Despre Noi',
      aboutDesc: 'Povestea Jubilee Luxury Design — peste 13 ani de excelență în design interior de lux în București.',
      portfolioTitle: 'Portofoliu',
      portfolioDesc: 'Descoperă proiectele noastre exclusive de design interior — penthouse-uri, vile și apartamente de lux.',
      servicesTitle: 'Servicii Premium',
      servicesDesc: 'Servicii complete de design interior: concept, execuție, mobilier premium. Consultație gratuită.',
      blogTitle: 'Blog Design Interior',
      blogDesc: 'Tendințe, sfaturi și inspirație în design interior de la experții Jubilee Luxury Design.',
      contactTitle: 'Contact',
      contactDesc: 'Programează o consultație gratuită de design interior. Str. Erou Iancu Nicolae 61, București.',
      shopTitle: 'Shop — Resurse pentru Designeri',
      shopDesc: 'Ebook-uri, template-uri și fișiere CAD premium pentru designeri și arhitecți.'
    }
  },
  en: {
    nav: {
      about: 'About Us',
      portfolio: 'Portfolio',
      services: 'Services',
      blog: 'Blog',
      shop: 'Shop',
      contact: 'Contact',
      callNow: 'Call Now'
    },
    home: {
      heroTitle: 'Interior Design Bucharest',
      heroSubtitle: 'We transform spaces into works of art through elegance, refinement and attention to detail',
      heroCta: 'Schedule a free consultation',
      aboutTitle: 'Excellence in',
      aboutHighlight: 'Interior Design',
      aboutDescription: 'With over 13 years of experience creating exclusive spaces, Jubilee Luxury Design combines art, functionality and elegance to create interiors that exceed expectations.',
      feature1: 'Personalized and exclusive design',
      feature2: 'Premium materials and luxury furniture',
      feature3: 'Complete turnkey services',
      readStory: 'Read our story',
      projectsTitle: 'Exclusive',
      projectsHighlight: 'Projects',
      projectsDescription: 'Each project is a unique story of elegance and refinement, specially created for our demanding clients',
      viewPortfolio: 'View full portfolio',
      ctaTitle: 'Ready to transform your space?',
      residential: 'Residential',
      commercial: 'Commercial',
      penthouse: 'Exclusive Penthouse',
      villa: 'Contemporary Villa',
      showroom: 'Premium Showroom',
      altBedroom: 'Luxury bedroom interior design',
      altKitchen: 'Luxury kitchen interior design',
      altLiving: 'Modern luxury living room interior design'
    },
    footer: {
      inspirationTitle: 'Inspiration &',
      inspirationHighlight: 'Trends',
      inspirationDescription: 'Receive monthly exclusive interior design ideas, trends and tips from Jubilee Luxury Design experts',
      emailPlaceholder: 'Your email address',
      subscribe: 'Subscribe',
      brandDescription: 'For over 13 years, we have been creating exclusive spaces that combine elegance with functionality, offering complete luxury interior design services for demanding clients.',
      services: 'Services',
      aboutUs: 'About Us',
      resources: 'Resources',
      completeDesign: 'Complete Interior Design',
      designConsultancy: 'Design Consultancy',
      premiumFurniture: 'Premium Furniture',
      commercialDesign: 'Commercial Design',
      ourStory: 'Our Story',
      portfolio: 'Portfolio',
      testimonials: 'Testimonials',
      designBlog: 'Design Blog',
      styleGuide: 'Style Guide',
      allRights: 'All rights reserved.',
      privacyPolicy: 'Privacy Policy',
      termsConditions: 'Terms and Conditions',
      cookiesPolicy: 'Cookies Policy',
      cookieSettings: 'Cookie Settings'
    },
    about: {
      heroTitle: 'The Story of',
      heroHighlight: 'Jubilee Luxury Design',
      heroDescription: 'For over 13 years, we have been creating exclusive spaces that reflect the personality and dreams of our clients',
      storyTitle: 'A Vision Born from Passion',
      storyP1: 'Jubilee Luxury Design was born in 2012 from a passion for beauty, functionality and the desire to transform each space into a unique work of art.',
      storyP2: 'Specializing in luxury interior design, we have developed a holistic approach that combines timeless elegance with contemporary innovation, creating interiors that transcend current trends.',
      storyP3: 'Our philosophy is based on the idea that each client is unique, and their home must reflect their personality, lifestyle and aspirations.',
      yearsExperience: 'Years of experience',
      completedProjects: 'Completed projects',
      happyClients: 'Happy clients',
      teamDescription: 'Experienced professionals dedicated to excellence in design',
      philosophyTitle: 'Our Philosophy',
      excellence: 'Excellence',
      excellenceDesc: 'Our high standards are reflected in every detail of the projects',
      personalization: 'Personalization',
      personalizationDesc: 'Each project is unique, perfectly adapted to the client\'s needs',
      exclusivity: 'Exclusivity',
      exclusivityDesc: 'Access to premium furniture and exclusive art pieces',
      startProject: 'Start your project'
    },
    services: {
      heroTitle: 'Premium',
      heroHighlight: 'Services',
      heroDescription: 'Our experience begins where your dream takes shape. Each project is treated with the attention and elegance it deserves, through complete service packages designed to accompany you every step — from the first sketches to the last decor detail.',
      heroDescription2: 'Everything is personalized: your pace, your style, your story. The result? A space that not only looks good but makes you feel at home.',
      completeDesignTitle: 'Complete Interior Design',
      completeDesignDesc: 'Our premium service for complete space transformation, from concept to turnkey.',
      consultancyTitle: 'Design Consultancy',
      consultancyDesc: 'Perfect for clients who want to implement the project through their own resources.',
      furnitureTitle: 'Premium Furniture Acquisition',
      furnitureDesc: 'Exclusive service for acquiring luxury furniture and accessories from our selected partners.',
      mostPopular: 'Most popular',
      requestQuote: 'Request quote',
      completeFeature1: 'Full concept and photorealistic 3D renders',
      completeFeature2: 'End-to-end execution supervision',
      completeFeature3: 'Luxury finishes and premium materials',
      completeFeature4: 'Detailed technical plans',
      completeFeature5: 'Supplier and craftsman coordination',
      completeFeature6: 'Post-completion consultancy included',
      consultancyFeature1: 'Detailed space analysis',
      consultancyFeature2: 'Mood boards and visual concept',
      consultancyFeature3: 'Custom color palette guide',
      consultancyFeature4: 'Furniture and decor recommendations',
      consultancyFeature5: '2D layout plans',
      consultancyFeature6: 'Detailed report and shopping list',
      furnitureFeature1: 'Access to exclusive showrooms',
      furnitureFeature2: 'Custom furniture design',
      furnitureFeature3: 'Premium Italian and European brands',
      furnitureFeature4: 'Delivery and installation coordination',
      furnitureFeature5: 'Textile and accessories selection consultancy',
      furnitureFeature6: 'Extended warranty on all products',
      processTitle: 'Our',
      processHighlight: 'Work Process',
      processDescription: 'A structured and transparent process for exceptional results',
      step1Title: 'Initial Consultation',
      step1Desc: 'Home meeting to analyze the space and understand your needs',
      step2Title: 'Concept Development',
      step2Desc: 'Creating the design concept and presenting the detailed proposal',
      step3Title: 'Detailed Planning',
      step3Desc: 'Technical plans, materials list and implementation schedule',
      step4Title: 'Implementation',
      step4Desc: 'Project execution with constant supervision from our team',
      duration: 'Duration',
      guaranteesTitle: 'Our',
      guaranteesHighlight: 'Guarantees',
      qualityGuarantee: 'Quality Guarantee',
      qualityDesc: 'Certified premium materials and the highest quality craftsmanship, guaranteed',
      budgetGuarantee: 'Budget Compliance',
      budgetDesc: 'Fixed price set from the start, no hidden or additional costs',
      deliveryGuarantee: 'On-Time Delivery',
      deliveryDesc: 'Adherence to established schedule or compensation for delays',
      ctaTitle: 'Ready to Start Your Project?',
      ctaDescription: 'The initial consultation is free and without obligation. Discover how we can transform your space.',
      scheduleFree: 'Schedule free consultation',
      duration1: '2-3 hours',
      duration2: '1-2 weeks',
      duration3: '1 week',
      duration4: '4-12 weeks'
    },
    portfolio: {
      heroTitle: 'Premium Portfolio',
      heroDescription: 'Our collection of exclusive projects that redefine the standards of elegance and refinement',
      all: 'All',
      residential: 'Residential',
      commercial: 'Commercial',
      penthouse: 'Penthouse',
      villa: 'Villa',
      viewDetails: 'View details',
      processTitle: 'Our Process',
      processDescription: 'Each project follows a rigorous process from concept to completion',
      consultation: 'Consultation',
      consultationDesc: 'Detailed analysis of your needs and dreams',
      concept: 'Concept',
      conceptDesc: 'Development of a unique and personalized vision',
      execution: 'Execution',
      executionDesc: 'Precise implementation with premium materials',
      finalization: 'Finalization',
      finalizationDesc: 'Delivery of a perfect and functional space',
      startProject: 'Start your project'
    },
    contact: {
      heroTitle: 'Let\'s Start',
      heroHighlight: 'Together',
      heroDescription: 'The initial consultation is free and without obligation. Contact us to discuss your dream',
      formTitle: 'Schedule Your',
      formHighlight: 'Free Consultation',
      fullName: 'Full name',
      namePlaceholder: 'Your name',
      email: 'Email',
      emailPlaceholder: 'email@example.com',
      phone: 'Phone',
      phonePlaceholder: '+40 732 456 789',
      projectType: 'Project type',
      selectProject: 'Select project type',
      projectDetails: 'Project details',
      detailsPlaceholder: 'Tell us more about your vision...',
      scheduleCta: 'Schedule Free Consultation',
      nextSteps: 'What happens after submitting the form?',
      step1: 'We contact you within 24 hours',
      step2: 'We schedule the consultation at the right time',
      step3: 'You receive a personalized proposal',
      phoneTitle: 'Phone',
      emailTitle: 'Email',
      officeTitle: 'Office',
      scheduleTitle: 'Schedule',
      callNow: 'Call now',
      sendEmail: 'Send email',
      viewOnMap: 'View on map',
      scheduleVisit: 'Schedule visit',
      uniqueExperience: 'A Unique Experience Awaits You',
      personalizedConsultancy: 'Personalized consultancy',
      freeParking: 'Free parking available',
      scheduleOfficeVisit: 'Schedule a visit to our office',
      openInMaps: 'Open in Google Maps',
      faqTitle: 'Frequently Asked',
      faqHighlight: 'Questions',
      faq1Q: 'How long does a project take?',
      faq1A: 'Between 4-12 weeks, depending on the complexity of the project and the area of the space.',
      faq2Q: 'What does the design service include?',
      faq2A: 'Our service includes concept, technical plans, 3D visualizations, supplier coordination and execution supervision.',
      faq3Q: 'Do you work nationwide?',
      faq3A: 'Yes, we accept projects throughout the country for areas of minimum 150sqm.',
      faq4Q: 'What is the minimum budget?',
      faq4A: 'The minimum budget for a complete project is €25,000, including furniture and execution.',
      viewAllFaq: 'View all frequently asked questions',
      successTitle: 'Message sent successfully!',
      successDescription: 'We will contact you within 24 hours to schedule the consultation.',
      gdprConsent: 'I agree to the',
      gdprPrivacyLink: 'Privacy Policy',
      gdprAnd: 'and',
      gdprTermsLink: 'Terms and Conditions',
      gdprRequired: 'You must accept the privacy policy to submit the form.',
      errorTitle: 'Submission Error',
      errorDescription: 'Could not send the message. Please contact us by phone.',
      service1: 'Complete Interior Design',
      service2: 'Design Consultancy',
      service3: 'Renovation & Redesign',
      service4: 'Premium Furniture Acquisition',
      service5: 'Commercial Design',
      service6: 'Other'
    },
    blog: {
      heroTitle: 'Design',
      heroHighlight: 'Blog',
      heroDescription: 'Inspiration, tips and trends in interior design from Interior Design Bucharest experts',
      all: 'All',
      trends: 'Trends',
      tips: 'Tips',
      design: 'Design',
      materials: 'Materials',
      readMore: 'Read more',
      readTime: 'min read',
      newsletterTitle: 'Stay up to date with the news',
      newsletterDescription: 'Subscribe to our newsletter to receive the latest articles and design tips.',
      emailPlaceholder: 'Your email address',
      subscribe: 'Subscribe'
    },
    shop: {
      heroTitle: 'Premium resources for designers and architects',
      heroDescription: 'Templates, ebooks and CAD files that optimize your time, clarify your process and elevate your presentations to a professional level.',
      enterShop: '👉 Enter Shop',
      categories: 'Categories',
      allProducts: 'All products',
      ebooks: 'Ebooks',
      templates: 'Templates',
      cadFiles: 'CAD Files',
      packages: 'Complete packages',
      viewProduct: 'View product',
      whyWorksTitle: 'Why do these resources work?',
      benefit1: 'Helps you save hours in the work process',
      benefit2: 'Present projects in a professional and convincing way',
      benefit3: 'Helps you clearly organize the entire client flow',
      benefit4: 'Premium documents inspired by international studios',
      benefit5: 'Better results and a premium experience for the client',
      testimonial1: 'The documents are beautiful and intuitive. They completely changed the way I present projects.',
      testimonial2: 'I immediately felt how a premium agency looks. The templates are gold.',
      ctaTitle: 'Find the resources that streamline your work',
      ctaDescription: 'Premium documents for architects and designers who want more: order, professionalism, efficiency.',
      buyNow: '👉 Buy now',
      comingSoon: 'Coming Soon',
      backToShop: 'Back to Shop',
      buyProduct: 'Buy Now',
      whatIsIncluded: "What's included",
      securePayment: 'Secure payment via Stripe',
      instantDelivery: 'Instant delivery after payment',
      relatedProducts: 'Related products'
    },
    products: {
      starterPack: {
        title: 'Client Starter Pack',
        description: 'Professional set for the first client interaction: guides, questionnaires and essential documents. Helps you create a clear, premium and coherent process from the first contact.',
        longDescription: 'The Client Starter Pack is the ideal resource for designers and architects who want to make a flawless first impression. The package contains all the documents needed to professionally manage the first meeting with the client: from detailed questionnaires to communication guides and organizational templates. Each element was created to help you save time and convey confidence from the very first moment.',
        feature1: 'Detailed questionnaire for the first meeting',
        feature2: 'Professional client communication guide',
        feature3: 'Project organization templates',
        feature4: 'Onboarding process checklist'
      },
      bathroomComplete: {
        title: 'Bathroom eBook + CAD Files + Template',
        description: 'Complete package for bathroom design: detailed ebook, CAD files + professional template. Everything you need for technically correct and aesthetically impeccable projects.',
        longDescription: 'This all-in-one package gives you everything you need for flawless bathroom projects. The ebook covers essential technical details, standard dimensions and layout solutions, the CAD files are ready to use in your projects, and the professional template allows you to present the client with a coherent and convincing concept.',
        feature1: 'Detailed ebook with bathroom dimensions and layouts',
        feature2: 'Editable and organized CAD files',
        feature3: 'Professional presentation template',
        feature4: 'Examples of completed projects'
      },
      beigeContract: {
        title: 'BEIGE – Contract & Price Quote Template',
        description: 'Elegant and easy-to-customize document for contracts and quotes. Built to convey professionalism and consistency in client relationships.',
        longDescription: 'The BEIGE template is the perfect solution for designers who want professional documents without effort. Created with attention to typographic and visual details, this template allows you to quickly generate contracts and price quotes that inspire trust. The elegant and neutral design fits any interior design brand.',
        feature1: 'Complete and customizable contract template',
        feature2: 'Price quote with premium design',
        feature3: 'Easy to edit and adapt format',
        feature4: 'Elegant design suitable for any brand'
      },
      greenPresentation: {
        title: 'GREEN – Company Presentation Template',
        description: 'Minimalist template, perfect for pitches, B2B collaborations, corporate meetings and presenting your agency.',
        longDescription: 'The GREEN template is designed to present your design agency in a professional and memorable way. With a minimalist and modern design, it is perfect for pitches, B2B meetings and corporate presentations. The slides are strategically organized to effectively communicate your story, services and portfolio.',
        feature1: 'Company presentation with minimalist design',
        feature2: 'Strategic slides for pitches',
        feature3: 'Sections for portfolio and services',
        feature4: 'Easy to customize with your brand'
      },
      kitchenEbook: {
        title: 'Kitchen eBook + CAD Files',
        description: 'Complete guide for kitchen design + organized CAD files. Ideal for fast, correct and super professional projects.',
        longDescription: 'The Kitchen eBook is an essential resource for any interior designer. It covers everything you need to know about kitchen design: from ergonomics and standard dimensions, to layout types and storage solutions. The included CAD files are organized by category and ready to integrate into your projects.',
        feature1: 'Complete ergonomics guide for kitchens',
        feature2: 'CAD files organized by category',
        feature3: 'Layout types and standard dimensions',
        feature4: 'Storage and space optimization solutions'
      },
      bathroomV2: {
        title: 'Bathroom eBook + CAD Files + Template (V2)',
        description: 'Alternative complete package for bathroom projects: technical details, CAD files + premium template for presentations.',
        longDescription: 'The V2 version of the bathroom package brings an updated design and expanded content. Includes a revised ebook with the latest trends, updated CAD files and a premium template with a fresh look. Ideal for designers who want to stay current with industry developments.',
        feature1: 'Revised ebook with current trends',
        feature2: 'Updated and expanded CAD files',
        feature3: 'Premium template with fresh design',
        feature4: 'Expanded content compared to previous version'
      },
      millworkGuide: {
        title: 'Millwork – Complete Custom Furniture Guide',
        description: 'Premium guide with standard dimensions, technical details, concrete examples for kitchens, closets, bookcases. The perfect resource for a faster, more coherent and safer workflow — no errors, no improvisation.',
        longDescription: 'The Millwork Guide is the definitive resource for designers working with custom furniture. It covers in detail standard dimensions, tolerances, joint types and materials for kitchens, closets, bookcases and other furniture pieces. With concrete examples and technical diagrams, this guide eliminates uncertainty and reduces errors in the design process.',
        feature1: 'Standard dimensions for all furniture types',
        feature2: 'Technical details for kitchens and closets',
        feature3: 'Concrete examples and technical diagrams',
        feature4: 'Materials guide and joint types'
      }
    },
    legal: {
      back: '← Back'
    },
    seo: {
      homeTitle: 'Interior Design Bucharest',
      homeDesc: 'Luxury interior design studio in Bucharest. Complete premium decoration services, design consultancy and exclusive furniture. Jubilee Luxury Design — 13+ years of experience.',
      aboutTitle: 'About Us',
      aboutDesc: 'The story of Jubilee Luxury Design — over 13 years of excellence in luxury interior design in Bucharest.',
      portfolioTitle: 'Portfolio',
      portfolioDesc: 'Discover our exclusive interior design projects — penthouses, villas and luxury apartments.',
      servicesTitle: 'Premium Services',
      servicesDesc: 'Complete interior design services: concept, execution, premium furniture. Free consultation.',
      blogTitle: 'Interior Design Blog',
      blogDesc: 'Trends, tips and inspiration in interior design from Jubilee Luxury Design experts.',
      contactTitle: 'Contact',
      contactDesc: 'Schedule a free interior design consultation. Str. Erou Iancu Nicolae 61, Bucharest.',
      shopTitle: 'Shop — Resources for Designers',
      shopDesc: 'Premium ebooks, templates and CAD files for designers and architects.'
    }
  },
  es: {
    nav: {
      about: 'Sobre Nosotros',
      portfolio: 'Portafolio',
      services: 'Servicios',
      blog: 'Blog',
      shop: 'Tienda',
      contact: 'Contacto',
      callNow: 'Llamar Ahora'
    },
    home: {
      heroTitle: 'Diseño Interior Bucarest',
      heroSubtitle: 'Transformamos espacios en obras de arte a través de la elegancia, el refinamiento y la atención al detalle',
      heroCta: 'Programa una consulta gratuita',
      aboutTitle: 'Excelencia en',
      aboutHighlight: 'Diseño Interior',
      aboutDescription: 'Con más de 13 años de experiencia creando espacios exclusivos, Jubilee Luxury Design combina arte, funcionalidad y elegancia para crear interiores que superan las expectativas.',
      feature1: 'Diseño personalizado y exclusivo',
      feature2: 'Materiales premium y mobiliario de lujo',
      feature3: 'Servicios completos llave en mano',
      readStory: 'Lee nuestra historia',
      projectsTitle: 'Proyectos',
      projectsHighlight: 'Exclusivos',
      projectsDescription: 'Cada proyecto es una historia única de elegancia y refinamiento, creada especialmente para nuestros clientes exigentes',
      viewPortfolio: 'Ver portafolio completo',
      ctaTitle: '¿Listo para transformar tu espacio?',
      residential: 'Residencial',
      commercial: 'Comercial',
      penthouse: 'Penthouse Exclusivo',
      villa: 'Villa Contemporánea',
      showroom: 'Showroom Premium',
      altBedroom: 'Diseño interior de dormitorio de lujo',
      altKitchen: 'Diseño interior de cocina de lujo',
      altLiving: 'Diseño interior moderno de sala de lujo'
    },
    footer: {
      inspirationTitle: 'Inspiración y',
      inspirationHighlight: 'Tendencias',
      inspirationDescription: 'Recibe mensualmente ideas exclusivas de diseño interior, tendencias y consejos de los expertos de Jubilee Luxury Design',
      emailPlaceholder: 'Tu correo electrónico',
      subscribe: 'Suscribirse',
      brandDescription: 'Durante más de 13 años, hemos creado espacios exclusivos que combinan elegancia con funcionalidad, ofreciendo servicios completos de diseño interior de lujo para clientes exigentes.',
      services: 'Servicios',
      aboutUs: 'Sobre Nosotros',
      resources: 'Recursos',
      completeDesign: 'Diseño Interior Completo',
      designConsultancy: 'Consultoría de Diseño',
      premiumFurniture: 'Mobiliario Premium',
      commercialDesign: 'Diseño Comercial',
      ourStory: 'Nuestra Historia',
      portfolio: 'Portafolio',
      testimonials: 'Testimonios',
      designBlog: 'Blog de Diseño',
      styleGuide: 'Guía de Estilos',
      allRights: 'Todos los derechos reservados.',
      privacyPolicy: 'Política de Privacidad',
      termsConditions: 'Términos y Condiciones',
      cookiesPolicy: 'Política de Cookies',
      cookieSettings: 'Configuración de cookies'
    },
    about: {
      heroTitle: 'La Historia de',
      heroHighlight: 'Jubilee Luxury Design',
      heroDescription: 'Durante más de 13 años, hemos creado espacios exclusivos que reflejan la personalidad y los sueños de nuestros clientes',
      storyTitle: 'Una Visión Nacida de la Pasión',
      storyP1: 'Jubilee Luxury Design nació en 2012 de una pasión por la belleza, la funcionalidad y el deseo de transformar cada espacio en una obra de arte única.',
      storyP2: 'Especializándonos en diseño interior de lujo, hemos desarrollado un enfoque holístico que combina la elegancia atemporal con la innovación contemporánea, creando interiores que trascienden las tendencias actuales.',
      storyP3: 'Nuestra filosofía se basa en la idea de que cada cliente es único, y su hogar debe reflejar su personalidad, estilo de vida y aspiraciones.',
      yearsExperience: 'Años de experiencia',
      completedProjects: 'Proyectos completados',
      happyClients: 'Clientes satisfechos',
      teamDescription: 'Profesionales experimentados dedicados a la excelencia en diseño',
      philosophyTitle: 'Nuestra Filosofía',
      excellence: 'Excelencia',
      excellenceDesc: 'Nuestros altos estándares se reflejan en cada detalle de los proyectos',
      personalization: 'Personalización',
      personalizationDesc: 'Cada proyecto es único, perfectamente adaptado a las necesidades del cliente',
      exclusivity: 'Exclusividad',
      exclusivityDesc: 'Acceso a mobiliario premium y piezas de arte exclusivas',
      startProject: 'Inicia tu proyecto'
    },
    services: {
      heroTitle: 'Servicios',
      heroHighlight: 'Premium',
      heroDescription: 'Nuestra experiencia comienza donde tu sueño toma forma. Cada proyecto es tratado con la atención y elegancia que merece, a través de paquetes completos de servicios diseñados para acompañarte en cada paso — desde los primeros bocetos hasta el último detalle de decoración.',
      heroDescription2: 'Todo es personalizado: tu ritmo, tu estilo, tu historia. ¿El resultado? Un espacio que no solo luce bien, sino que te hace sentir en casa.',
      completeDesignTitle: 'Diseño Interior Completo',
      completeDesignDesc: 'Nuestro servicio premium para la transformación completa del espacio, desde el concepto hasta llave en mano.',
      consultancyTitle: 'Consultoría de Diseño',
      consultancyDesc: 'Perfecto para clientes que desean implementar el proyecto con sus propios recursos.',
      furnitureTitle: 'Adquisición de Mobiliario Premium',
      furnitureDesc: 'Servicio exclusivo de adquisición de mobiliario y accesorios de lujo de nuestros socios seleccionados.',
      mostPopular: 'Más popular',
      requestQuote: 'Solicitar presupuesto',
      completeFeature1: 'Concepto completo y renders 3D fotorrealistas',
      completeFeature2: 'Supervisión de ejecución de principio a fin',
      completeFeature3: 'Acabados de lujo y materiales premium',
      completeFeature4: 'Planos técnicos detallados',
      completeFeature5: 'Coordinación de proveedores y artesanos',
      completeFeature6: 'Consultoría post-finalización incluida',
      consultancyFeature1: 'Análisis detallado del espacio',
      consultancyFeature2: 'Mood boards y concepto visual',
      consultancyFeature3: 'Guía de paleta cromática personalizada',
      consultancyFeature4: 'Recomendaciones de mobiliario y decoración',
      consultancyFeature5: 'Planos de distribución 2D',
      consultancyFeature6: 'Informe detallado y lista de compras',
      furnitureFeature1: 'Acceso a showrooms exclusivos',
      furnitureFeature2: 'Diseño de mobiliario personalizado',
      furnitureFeature3: 'Marcas italianas y europeas premium',
      furnitureFeature4: 'Coordinación de entrega e instalación',
      furnitureFeature5: 'Consultoría de selección de textiles y accesorios',
      furnitureFeature6: 'Garantía extendida en todos los productos',
      processTitle: 'Nuestro Proceso de',
      processHighlight: 'Trabajo',
      processDescription: 'Un proceso estructurado y transparente para resultados excepcionales',
      step1Title: 'Consulta Inicial',
      step1Desc: 'Reunión a domicilio para analizar el espacio y entender tus necesidades',
      step2Title: 'Desarrollo del Concepto',
      step2Desc: 'Creación del concepto de diseño y presentación de la propuesta detallada',
      step3Title: 'Planificación Detallada',
      step3Desc: 'Planos técnicos, lista de materiales y cronograma de implementación',
      step4Title: 'Implementación',
      step4Desc: 'Ejecución del proyecto con supervisión constante de nuestro equipo',
      duration: 'Duración',
      guaranteesTitle: 'Nuestras',
      guaranteesHighlight: 'Garantías',
      qualityGuarantee: 'Garantía de Calidad',
      qualityDesc: 'Materiales premium certificados y mano de obra de la más alta calidad, garantizada',
      budgetGuarantee: 'Cumplimiento del Presupuesto',
      budgetDesc: 'Precio fijo establecido desde el inicio, sin costos ocultos o adicionales',
      deliveryGuarantee: 'Entrega a Tiempo',
      deliveryDesc: 'Cumplimiento del programa establecido o compensación por retrasos',
      ctaTitle: '¿Listo para Iniciar tu Proyecto?',
      ctaDescription: 'La consulta inicial es gratuita y sin compromiso. Descubre cómo podemos transformar tu espacio.',
      scheduleFree: 'Programa consulta gratuita',
      duration1: '2-3 horas',
      duration2: '1-2 semanas',
      duration3: '1 semana',
      duration4: '4-12 semanas'
    },
    portfolio: {
      heroTitle: 'Portafolio Premium',
      heroDescription: 'Nuestra colección de proyectos exclusivos que redefinen los estándares de elegancia y refinamiento',
      all: 'Todos',
      residential: 'Residencial',
      commercial: 'Comercial',
      penthouse: 'Penthouse',
      villa: 'Villa',
      viewDetails: 'Ver detalles',
      processTitle: 'Nuestro Proceso',
      processDescription: 'Cada proyecto sigue un proceso riguroso desde el concepto hasta la finalización',
      consultation: 'Consulta',
      consultationDesc: 'Análisis detallado de tus necesidades y sueños',
      concept: 'Concepto',
      conceptDesc: 'Desarrollo de una visión única y personalizada',
      execution: 'Ejecución',
      executionDesc: 'Implementación precisa con materiales premium',
      finalization: 'Finalización',
      finalizationDesc: 'Entrega de un espacio perfecto y funcional',
      startProject: 'Inicia tu proyecto'
    },
    contact: {
      heroTitle: 'Comencemos',
      heroHighlight: 'Juntos',
      heroDescription: 'La consulta inicial es gratuita y sin compromiso. Contáctanos para hablar sobre tu sueño',
      formTitle: 'Programa tu Consulta',
      formHighlight: 'Gratuita',
      fullName: 'Nombre completo',
      namePlaceholder: 'Tu nombre',
      email: 'Correo electrónico',
      emailPlaceholder: 'email@ejemplo.com',
      phone: 'Teléfono',
      phonePlaceholder: '+40 732 456 789',
      projectType: 'Tipo de proyecto',
      selectProject: 'Selecciona el tipo de proyecto',
      projectDetails: 'Detalles del proyecto',
      detailsPlaceholder: 'Cuéntanos más sobre tu visión...',
      scheduleCta: 'Programa Consulta Gratuita',
      nextSteps: '¿Qué sucede después de enviar el formulario?',
      step1: 'Te contactamos en máximo 24 horas',
      step2: 'Programamos la consulta en el momento adecuado',
      step3: 'Recibes una propuesta personalizada',
      phoneTitle: 'Teléfono',
      emailTitle: 'Correo',
      officeTitle: 'Oficina',
      scheduleTitle: 'Horario',
      callNow: 'Llamar ahora',
      sendEmail: 'Enviar correo',
      viewOnMap: 'Ver en mapa',
      scheduleVisit: 'Programar visita',
      uniqueExperience: 'Una Experiencia Única te Espera',
      personalizedConsultancy: 'Consultoría personalizada',
      freeParking: 'Estacionamiento gratuito disponible',
      scheduleOfficeVisit: 'Programa una visita a nuestra oficina',
      openInMaps: 'Abrir en Google Maps',
      faqTitle: 'Preguntas',
      faqHighlight: 'Frecuentes',
      faq1Q: '¿Cuánto tiempo dura un proyecto?',
      faq1A: 'Entre 4-12 semanas, dependiendo de la complejidad del proyecto y el área del espacio.',
      faq2Q: '¿Qué incluye el servicio de diseño?',
      faq2A: 'Nuestro servicio incluye concepto, planos técnicos, visualizaciones 3D, coordinación de proveedores y supervisión de ejecución.',
      faq3Q: '¿Trabajan en todo el país?',
      faq3A: 'Sí, aceptamos proyectos en todo el país para áreas de mínimo 150m².',
      faq4Q: '¿Cuál es el presupuesto mínimo?',
      faq4A: 'El presupuesto mínimo para un proyecto completo es de €25,000, incluyendo mobiliario y ejecución.',
      viewAllFaq: 'Ver todas las preguntas frecuentes',
      successTitle: '¡Mensaje enviado con éxito!',
      successDescription: 'Te contactaremos en máximo 24 horas para programar la consulta.',
      gdprConsent: 'Acepto la',
      gdprPrivacyLink: 'Política de Privacidad',
      gdprAnd: 'y los',
      gdprTermsLink: 'Términos y Condiciones',
      gdprRequired: 'Debe aceptar la política de privacidad para enviar el formulario.',
      errorTitle: 'Error de envío',
      errorDescription: 'No se pudo enviar el mensaje. Por favor contáctenos por teléfono.',
      service1: 'Diseño Interior Completo',
      service2: 'Consultoría de Diseño',
      service3: 'Renovación y Rediseño',
      service4: 'Adquisición de Mobiliario Premium',
      service5: 'Diseño Comercial',
      service6: 'Otros'
    },
    blog: {
      heroTitle: 'Blog de',
      heroHighlight: 'Diseño',
      heroDescription: 'Inspiración, consejos y tendencias en diseño interior de los expertos de Diseño Interior Bucarest',
      all: 'Todos',
      trends: 'Tendencias',
      tips: 'Consejos',
      design: 'Diseño',
      materials: 'Materiales',
      readMore: 'Leer más',
      readTime: 'min lectura',
      newsletterTitle: 'Mantente al día con las novedades',
      newsletterDescription: 'Suscríbete a nuestro boletín para recibir los últimos artículos y consejos de diseño.',
      emailPlaceholder: 'Tu correo electrónico',
      subscribe: 'Suscribirse'
    },
    shop: {
      heroTitle: 'Recursos premium para diseñadores y arquitectos',
      heroDescription: 'Plantillas, ebooks y archivos CAD que optimizan tu tiempo, clarifican tu proceso y elevan tus presentaciones a nivel profesional.',
      enterShop: '👉 Entrar a la Tienda',
      categories: 'Categorías',
      allProducts: 'Todos los productos',
      ebooks: 'Ebooks',
      templates: 'Plantillas',
      cadFiles: 'Archivos CAD',
      packages: 'Paquetes completos',
      viewProduct: 'Ver producto',
      whyWorksTitle: '¿Por qué funcionan estos recursos?',
      benefit1: 'Te ayuda a ahorrar horas en el proceso de trabajo',
      benefit2: 'Presenta proyectos de manera profesional y convincente',
      benefit3: 'Te ayuda a organizar claramente todo el flujo con el cliente',
      benefit4: 'Documentos premium inspirados en estudios internacionales',
      benefit5: 'Mejores resultados y una experiencia premium para el cliente',
      testimonial1: 'Los documentos son hermosos e intuitivos. Cambiaron completamente la forma en que presento proyectos.',
      testimonial2: 'Inmediatamente sentí cómo se ve una agencia premium. Las plantillas son oro.',
      ctaTitle: 'Encuentra los recursos que optimizan tu trabajo',
      ctaDescription: 'Documentos premium para arquitectos y diseñadores que quieren más: orden, profesionalismo, eficiencia.',
      buyNow: '👉 Comprar ahora',
      comingSoon: 'Próximamente',
      backToShop: 'Volver a la Tienda',
      buyProduct: 'Comprar',
      whatIsIncluded: 'Qué incluye',
      securePayment: 'Pago seguro vía Stripe',
      instantDelivery: 'Entrega instantánea después del pago',
      relatedProducts: 'Productos similares'
    },
    products: {
      starterPack: {
        title: 'Starter Pack Cliente',
        description: 'Set profesional para la primera interacción con un cliente: guías, cuestionarios y documentos esenciales. Te ayuda a crear un proceso claro, premium y coherente desde el primer contacto.',
        longDescription: 'El Starter Pack Cliente es el recurso ideal para diseñadores y arquitectos que quieren causar una primera impresión impecable. El paquete contiene todos los documentos necesarios para gestionar profesionalmente la primera reunión con el cliente: desde cuestionarios detallados hasta guías de comunicación y plantillas de organización. Cada elemento fue creado para ayudarte a ahorrar tiempo y transmitir confianza desde el primer momento.',
        feature1: 'Cuestionario detallado para la primera reunión',
        feature2: 'Guía profesional de comunicación con el cliente',
        feature3: 'Plantillas de organización del proyecto',
        feature4: 'Checklist para el proceso de onboarding'
      },
      bathroomComplete: {
        title: 'Bathroom eBook + Archivos CAD + Plantilla',
        description: 'Paquete completo para el diseño de baños: ebook detallado, archivos CAD + plantilla profesional. Todo lo que necesitas para proyectos técnicamente correctos y estéticamente impecables.',
        longDescription: 'Este paquete todo-en-uno te ofrece todo lo que necesitas para proyectos de baños impecables. El ebook cubre detalles técnicos esenciales, dimensiones estándar y soluciones de layout, los archivos CAD están listos para usar en tus proyectos, y la plantilla profesional te permite presentar al cliente un concepto coherente y convincente.',
        feature1: 'Ebook detallado con dimensiones y layouts para baños',
        feature2: 'Archivos CAD editables y organizados',
        feature3: 'Plantilla profesional para presentaciones',
        feature4: 'Ejemplos de proyectos finalizados'
      },
      beigeContract: {
        title: 'BEIGE – Plantilla Contrato y Oferta de Precio',
        description: 'Documento elegante y fácil de personalizar para contratos y ofertas. Construido para transmitir profesionalismo y consistencia en la relación con el cliente.',
        longDescription: 'La plantilla BEIGE es la solución perfecta para diseñadores que quieren documentos profesionales sin esfuerzo. Creada con atención a los detalles tipográficos y visuales, esta plantilla te permite generar rápidamente contratos y ofertas de precio que inspiran confianza. El diseño elegante y neutro se adapta a cualquier marca de diseño interior.',
        feature1: 'Plantilla de contrato completa y personalizable',
        feature2: 'Oferta de precio con diseño premium',
        feature3: 'Formato fácil de editar y adaptar',
        feature4: 'Diseño elegante, adecuado para cualquier marca'
      },
      greenPresentation: {
        title: 'GREEN – Plantilla Presentación de Empresa',
        description: 'Plantilla minimalista, perfecta para pitches, colaboraciones B2B, reuniones corporativas y la presentación de tu agencia.',
        longDescription: 'La plantilla GREEN está diseñada para presentar tu agencia de diseño de manera profesional y memorable. Con un diseño minimalista y moderno, es perfecta para pitches, reuniones B2B y presentaciones corporativas. Las diapositivas están organizadas estratégicamente para comunicar eficazmente tu historia, servicios y portafolio.',
        feature1: 'Presentación de empresa con diseño minimalista',
        feature2: 'Diapositivas estratégicas para pitches',
        feature3: 'Secciones para portafolio y servicios',
        feature4: 'Fácil de personalizar con tu marca'
      },
      kitchenEbook: {
        title: 'Kitchen eBook + Archivos CAD',
        description: 'Guía completa para el diseño de cocinas + archivos CAD organizados. Ideal para proyectos rápidos, correctos y super profesionales.',
        longDescription: 'El eBook de cocina es un recurso esencial para cualquier diseñador de interiores. Cubre todo lo que necesitas saber sobre el diseño de cocinas: desde ergonomía y dimensiones estándar, hasta tipos de layouts y soluciones de almacenamiento. Los archivos CAD incluidos están organizados por categoría y listos para integrar en tus proyectos.',
        feature1: 'Guía completa de ergonomía para cocinas',
        feature2: 'Archivos CAD organizados por categoría',
        feature3: 'Tipos de layouts y dimensiones estándar',
        feature4: 'Soluciones de almacenamiento y optimización del espacio'
      },
      bathroomV2: {
        title: 'Bathroom eBook + Archivos CAD + Plantilla (V2)',
        description: 'Paquete completo alternativo para proyectos de baños: detalles técnicos, archivos CAD + plantilla premium para presentaciones.',
        longDescription: 'La versión V2 del paquete de baños trae un diseño actualizado y contenido ampliado. Incluye un ebook revisado con las últimas tendencias, archivos CAD actualizados y una plantilla premium con un look fresco. Ideal para diseñadores que quieren mantenerse al día con las novedades de la industria.',
        feature1: 'Ebook revisado con tendencias actuales',
        feature2: 'Archivos CAD actualizados y ampliados',
        feature3: 'Plantilla premium con diseño fresco',
        feature4: 'Contenido ampliado respecto a la versión anterior'
      },
      millworkGuide: {
        title: 'Millwork – Guía completa de mobiliario custom',
        description: 'Guía premium con dimensiones estándar, detalles técnicos, ejemplos concretos para cocinas, vestidores, bibliotecas. El recurso perfecto para un flujo de trabajo más rápido, coherente y seguro — sin errores, sin improvisaciones.',
        longDescription: 'La Guía Millwork es el recurso definitivo para diseñadores que trabajan con mobiliario custom. Cubre en detalle dimensiones estándar, tolerancias, tipos de uniones y materiales para cocinas, vestidores, bibliotecas y otras piezas de mobiliario. Con ejemplos concretos y diagramas técnicos, esta guía elimina la incertidumbre y reduce los errores en el proceso de diseño.',
        feature1: 'Dimensiones estándar para todos los tipos de mobiliario',
        feature2: 'Detalles técnicos para cocinas y vestidores',
        feature3: 'Ejemplos concretos y diagramas técnicos',
        feature4: 'Guía de materiales y tipos de uniones'
      }
    },
    legal: {
      back: '← Volver'
    },
    seo: {
      homeTitle: 'Diseño Interior Bucarest',
      homeDesc: 'Estudio de diseño interior de lujo en Bucarest. Servicios completos de decoración premium, consultoría de diseño y mobiliario exclusivo. Jubilee Luxury Design — 13+ años de experiencia.',
      aboutTitle: 'Sobre Nosotros',
      aboutDesc: 'La historia de Jubilee Luxury Design — más de 13 años de excelencia en diseño interior de lujo en Bucarest.',
      portfolioTitle: 'Portafolio',
      portfolioDesc: 'Descubre nuestros proyectos exclusivos de diseño interior — penthouses, villas y apartamentos de lujo.',
      servicesTitle: 'Servicios Premium',
      servicesDesc: 'Servicios completos de diseño interior: concepto, ejecución, mobiliario premium. Consulta gratuita.',
      blogTitle: 'Blog de Diseño Interior',
      blogDesc: 'Tendencias, consejos e inspiración en diseño interior de los expertos de Jubilee Luxury Design.',
      contactTitle: 'Contacto',
      contactDesc: 'Programa una consulta gratuita de diseño interior. Str. Erou Iancu Nicolae 61, Bucarest.',
      shopTitle: 'Tienda — Recursos para Diseñadores',
      shopDesc: 'Ebooks, plantillas y archivos CAD premium para diseñadores y arquitectos.'
    }
  }
};

export default LanguageContext;
