import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ro' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'ro';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, any>> = {
  ro: {
    nav: {
      about: 'Despre noi',
      portfolio: 'Portofoliu',
      services: 'Servicii',
      blog: 'Blog',
      shop: 'Shop',
      contact: 'Contact',
      callNow: 'Sună acum'
    },
    home: {
      heroTitle: 'Design Interior București',
      heroSubtitle: 'Transformăm spațiile în opere de artă prin eleganță, rafinament și atenție la detalii',
      heroCta: 'Programează o consultație gratuită',
      aboutTitle: 'Excelența în',
      aboutHighlight: 'Design Interior',
      aboutDescription: 'Cu peste 13 ani de experiență în crearea de spații exclusive, Jubilee Luxury Design îmbină artă, funcționalitate și eleganță pentru a realiza interioare care depășesc așteptările.',
      feature1: 'Design personalizat și exclusivist',
      feature2: 'Materiale premium și mobilier de lux',
      feature3: 'Servicii complete turnkey',
      readStory: 'Citește povestea noastră',
      projectsTitle: 'Proiecte',
      projectsHighlight: 'Exclusive',
      projectsDescription: 'Fiecare proiect este o poveste unică de eleganță și rafinament, creată special pentru clienții noștri exigenți',
      viewPortfolio: 'Vezi tot portofoliul',
      ctaTitle: 'Pregătit să îți transformi spațiul?',
      residential: 'Rezidențial',
      commercial: 'Comercial',
      penthouse: 'Penthouse Exclusivist',
      villa: 'Villa Contemporană',
      showroom: 'Showroom Premium'
    },
    footer: {
      inspirationTitle: 'Inspirație &',
      inspirationHighlight: 'Tendințe',
      inspirationDescription: 'Primește lunar idei exclusive de design interior, tendințe și sfaturi de la experții Jubilee Luxury Design',
      emailPlaceholder: 'Adresa ta de email',
      subscribe: 'Abonează-te',
      brandDescription: 'De peste 13 ani, creăm spații exclusive care îmbină eleganța cu funcționalitatea, oferind servicii complete de design interior de lux pentru clienți exigenți.',
      services: 'Servicii',
      aboutUs: 'Despre noi',
      resources: 'Resurse',
      completeDesign: 'Design Interior Complet',
      designConsultancy: 'Consultanță Design',
      premiumFurniture: 'Mobilier Premium',
      commercialDesign: 'Design Comercial',
      ourStory: 'Povestea noastră',
      portfolio: 'Portofoliu',
      testimonials: 'Testimoniale',
      designBlog: 'Blog Design',
      styleGuide: 'Ghid Stiluri',
      allRights: 'Toate drepturile rezervate.',
      privacyPolicy: 'Politica de confidențialitate',
      termsConditions: 'Termeni și condiții',
      cookiesPolicy: 'Politica cookies'
    },
    about: {
      heroTitle: 'Povestea',
      heroHighlight: 'Jubilee Luxury Design',
      heroDescription: 'De peste 13 ani, creăm spații exclusive care reflectă personalitatea și visurile clienților noștri',
      storyTitle: 'O Viziune Născută din Pasiune',
      storyP1: 'Jubilee Luxury Design s-a născut în 2012 dintr-o pasiune pentru frumusețe, funcționalitate și dorința de a transforma fiecare spațiu într-o operă de artă unică.',
      storyP2: 'Specializându-ne în design interior de lux, am dezvoltat o abordare holistică care îmbină eleganța atemporală cu inovația contemporană, creând interioare care depășesc tendințele momentului.',
      storyP3: 'Filozofia noastră se bazează pe ideea că fiecare client este unic, iar casa sa trebuie să reflecte personalitatea, stilul de viață și aspirațiile sale.',
      yearsExperience: 'Ani de experiență',
      completedProjects: 'Proiecte finalizate',
      happyClients: 'Clienți mulțumiți',
      teamDescription: 'Profesioniști cu experiență, dedicați excelenței în design',
      philosophyTitle: 'Filozofia Noastră',
      excellence: 'Excelență',
      excellenceDesc: 'Standardele noastre înalte se reflectă în fiecare detaliu al proiectelor',
      personalization: 'Personalizare',
      personalizationDesc: 'Fiecare proiect este unic, adaptat perfect nevoilor clientului',
      exclusivity: 'Exclusivitate',
      exclusivityDesc: 'Acces la mobilier premium și piese de artă exclusiviste',
      startProject: 'Începe proiectul tău'
    },
    services: {
      heroTitle: 'Servicii',
      heroHighlight: 'Premium',
      heroDescription: 'Experiența noastră începe acolo unde visul tău prinde formă. Fiecare proiect este tratat cu atenția și eleganța pe care le merită, prin pachete complete de servicii, gândite să te însoțească în fiecare etapă — de la primele schițe până la ultimul detaliu de decor.',
      heroDescription2: 'Totul este personalizat: ritmul tău, stilul tău, povestea ta. Rezultatul? Un spațiu care nu doar arată bine, ci te face să simți că ești acasă.',
      completeDesignTitle: 'Design Interior Complet',
      completeDesignDesc: 'Serviciul nostru premium pentru transformarea completă a spațiului, de la concept la cheie în mână.',
      consultancyTitle: 'Consultanță Design',
      consultancyDesc: 'Perfect pentru clienții care doresc să implementeze proiectul prin resurse proprii.',
      furnitureTitle: 'Achiziție Mobilier Premium',
      furnitureDesc: 'Serviciu exclusiv de achiziție mobilier și accesorii de lux de la partenerii noștri selectați.',
      mostPopular: 'Cel mai popular',
      requestQuote: 'Solicită ofertă',
      feature1: 'Concept și planuri detaliate',
      feature2: 'Mobilier și decorațiuni premium',
      feature3: 'Supraveghere completă execuție',
      feature4: 'Garanție 2 ani pentru toate lucrările',
      feature5: 'Materiale și finisaje de lux',
      feature6: 'Consultanță post-finalizare',
      processTitle: 'Procesul Nostru de',
      processHighlight: 'Lucru',
      processDescription: 'Un proces structurat și transparent pentru rezultate excepționale',
      step1Title: 'Consultația Inițială',
      step1Desc: 'Întâlnire la domiciliu pentru analiza spațiului și înțelegerea nevoilor tale',
      step2Title: 'Dezvoltarea Conceptului',
      step2Desc: 'Crearea conceptului de design și prezentarea propunerii detaliate',
      step3Title: 'Planificare Detaliată',
      step3Desc: 'Planuri tehnice, lista de materiale și cronograma de implementare',
      step4Title: 'Implementarea',
      step4Desc: 'Execuția proiectului cu supravegherea constantă a echipei noastre',
      duration: 'Durată',
      guaranteesTitle: 'Garanțiile',
      guaranteesHighlight: 'Noastre',
      qualityGuarantee: 'Garanție Calitate',
      qualityDesc: '2 ani garanție completă pentru toate lucrările și materialele utilizate',
      budgetGuarantee: 'Respectarea Bugetului',
      budgetDesc: 'Preț fix stabilit de la început, fără costuri ascunse sau suplimentare',
      deliveryGuarantee: 'Livrare la Timp',
      deliveryDesc: 'Respectarea programului stabilit sau compensare pentru întârzieri',
      ctaTitle: 'Pregătit să Începi Proiectul?',
      ctaDescription: 'Consultația inițială este gratuită și fără obligații. Descoperă cum putem transforma spațiul tău.',
      scheduleFree: 'Programează consultația gratuită'
    },
    portfolio: {
      heroTitle: 'Portofoliu Premium',
      heroDescription: 'Colecția noastră de proiecte exclusive care redefinesc standardele de eleganță și rafinament',
      all: 'Toate',
      residential: 'Rezidențial',
      commercial: 'Comercial',
      penthouse: 'Penthouse',
      villa: 'Villa',
      viewDetails: 'Vezi detalii',
      processTitle: 'Procesul Nostru',
      processDescription: 'Fiecare proiect urmează un proces riguros de la concept la finalizare',
      consultation: 'Consultația',
      consultationDesc: 'Analiză detaliată a nevoilor și visurilor tale',
      concept: 'Conceptul',
      conceptDesc: 'Dezvoltarea unei viziuni unice și personalizate',
      execution: 'Execuția',
      executionDesc: 'Implementare precisă cu materiale premium',
      finalization: 'Finalizarea',
      finalizationDesc: 'Predarea unui spațiu perfect și funcțional',
      startProject: 'Începe proiectul tău'
    },
    contact: {
      heroTitle: 'Să Începem',
      heroHighlight: 'Împreună',
      heroDescription: 'Consultația inițială este gratuită și fără obligații. Contactează-ne pentru a discuta despre visul tău',
      formTitle: 'Programează Consultația',
      formHighlight: 'Gratuită',
      fullName: 'Nume complet',
      namePlaceholder: 'Numele tău',
      email: 'Email',
      emailPlaceholder: 'email@exemplu.com',
      phone: 'Telefon',
      phonePlaceholder: '+40 732 456 789',
      projectType: 'Tip proiect',
      selectProject: 'Selectează tipul proiectului',
      projectDetails: 'Detalii despre proiect',
      detailsPlaceholder: 'Spune-ne mai multe despre viziunea ta...',
      scheduleCta: 'Programează Consultația Gratuită',
      nextSteps: 'Ce urmează după trimiterea formularului?',
      step1: 'Te contactăm în maxim 24 de ore',
      step2: 'Programăm consultația la momentul potrivit',
      step3: 'Primești o propunere personalizată',
      phoneTitle: 'Telefon',
      emailTitle: 'Email',
      officeTitle: 'Birou',
      scheduleTitle: 'Program',
      callNow: 'Sună acum',
      sendEmail: 'Trimite email',
      viewOnMap: 'Vezi pe hartă',
      scheduleVisit: 'Programează vizită',
      uniqueExperience: 'O Experiență Unică te Așteaptă',
      personalizedConsultancy: 'Consultanță personalizată',
      freeParking: 'Parcare gratuită disponibilă',
      scheduleOfficeVisit: 'Programează vizita la biroul nostru',
      openInMaps: 'Deschide în Google Maps',
      faqTitle: 'Întrebări',
      faqHighlight: 'Frecvente',
      faq1Q: 'Cât durează un proiect?',
      faq1A: 'Între 4-12 săptămâni, în funcție de complexitatea proiectului și suprafața spațiului.',
      faq2Q: 'Oferiți garanție?',
      faq2A: 'Da, oferim 2 ani garanție completă pentru toate lucrările și materialele utilizate.',
      faq3Q: 'Lucrați în toată țara?',
      faq3A: 'Da, acceptăm proiecte în întreaga țară pentru suprafețe de minimum 150mp.',
      faq4Q: 'Care este bugetul minim?',
      faq4A: 'Bugetul minim pentru un proiect complet este de 25.000€, inclusiv mobilier și execuție.',
      viewAllFaq: 'Vezi toate întrebările frecvente',
      successTitle: 'Mesaj trimis cu succes!',
      successDescription: 'Vă vom contacta în maxim 24 de ore pentru programarea consultației.'
    },
    blog: {
      heroTitle: 'Blog',
      heroHighlight: 'Design',
      heroDescription: 'Inspirație, sfaturi și tendințe în design interior de la experții Design Interior București',
      all: 'Toate',
      trends: 'Tendințe',
      tips: 'Sfaturi',
      design: 'Design',
      materials: 'Materiale',
      readMore: 'Citește mai mult',
      readTime: 'min citire',
      newsletterTitle: 'Rămâi la curent cu noutățile',
      newsletterDescription: 'Abonează-te la newsletter-ul nostru pentru a primi cele mai noi articole și sfaturi de design.',
      emailPlaceholder: 'Adresa ta de email',
      subscribe: 'Abonează-te'
    },
    shop: {
      heroTitle: 'Resurse premium pentru designeri și arhitecți',
      heroDescription: 'Template-uri, ebook-uri și fișiere CAD care îți optimizează timpul, îți clarifică procesul și îți ridică prezentările la nivel profesionist.',
      enterShop: '👉 Intră în Shop',
      categories: 'Categorii',
      allProducts: 'Toate produsele',
      ebooks: 'Ebook-uri',
      templates: 'Template-uri',
      cadFiles: 'Fișiere CAD',
      packages: 'Pachete complete',
      viewProduct: 'Vezi produsul',
      whyWorksTitle: 'De ce funcționează aceste resurse?',
      benefit1: 'Te ajută să economisești ore întregi în procesul de lucru',
      benefit2: 'Prezinți proiectele într-un mod profesionist și convingător',
      benefit3: 'Te ajută să-ți organizezi clar tot fluxul cu clientul',
      benefit4: 'Documente premium inspirate de studiouri internaționale',
      benefit5: 'Rezultate mai bune și o experiență premium pentru client',
      testimonial1: 'Documentele sunt superbe și intuitive. Mi-au schimbat complet modul în care prezint proiectele.',
      testimonial2: 'Am simțit imediat cum arată o agenție premium. Template-urile sunt aur.',
      ctaTitle: 'Găsește resursele care îți eficientizează munca',
      ctaDescription: 'Documente premium pentru arhitecți și designeri care vor mai mult: ordine, profesionalism, eficiență.',
      buyNow: '👉 Cumpără acum'
    }
  },
  en: {
    nav: {
      about: 'About Us',
      portfolio: 'Portfolio',
      services: 'Services',
      blog: 'Blog',
      shop: 'Shop',
      contact: 'Contact',
      callNow: 'Call Now'
    },
    home: {
      heroTitle: 'Interior Design Bucharest',
      heroSubtitle: 'We transform spaces into works of art through elegance, refinement and attention to detail',
      heroCta: 'Schedule a free consultation',
      aboutTitle: 'Excellence in',
      aboutHighlight: 'Interior Design',
      aboutDescription: 'With over 13 years of experience creating exclusive spaces, Jubilee Luxury Design combines art, functionality and elegance to create interiors that exceed expectations.',
      feature1: 'Personalized and exclusive design',
      feature2: 'Premium materials and luxury furniture',
      feature3: 'Complete turnkey services',
      readStory: 'Read our story',
      projectsTitle: 'Exclusive',
      projectsHighlight: 'Projects',
      projectsDescription: 'Each project is a unique story of elegance and refinement, specially created for our demanding clients',
      viewPortfolio: 'View full portfolio',
      ctaTitle: 'Ready to transform your space?',
      residential: 'Residential',
      commercial: 'Commercial',
      penthouse: 'Exclusive Penthouse',
      villa: 'Contemporary Villa',
      showroom: 'Premium Showroom'
    },
    footer: {
      inspirationTitle: 'Inspiration &',
      inspirationHighlight: 'Trends',
      inspirationDescription: 'Receive monthly exclusive interior design ideas, trends and tips from Jubilee Luxury Design experts',
      emailPlaceholder: 'Your email address',
      subscribe: 'Subscribe',
      brandDescription: 'For over 13 years, we have been creating exclusive spaces that combine elegance with functionality, offering complete luxury interior design services for demanding clients.',
      services: 'Services',
      aboutUs: 'About Us',
      resources: 'Resources',
      completeDesign: 'Complete Interior Design',
      designConsultancy: 'Design Consultancy',
      premiumFurniture: 'Premium Furniture',
      commercialDesign: 'Commercial Design',
      ourStory: 'Our Story',
      portfolio: 'Portfolio',
      testimonials: 'Testimonials',
      designBlog: 'Design Blog',
      styleGuide: 'Style Guide',
      allRights: 'All rights reserved.',
      privacyPolicy: 'Privacy Policy',
      termsConditions: 'Terms and Conditions',
      cookiesPolicy: 'Cookies Policy'
    },
    about: {
      heroTitle: 'The Story of',
      heroHighlight: 'Jubilee Luxury Design',
      heroDescription: 'For over 13 years, we have been creating exclusive spaces that reflect the personality and dreams of our clients',
      storyTitle: 'A Vision Born from Passion',
      storyP1: 'Jubilee Luxury Design was born in 2012 from a passion for beauty, functionality and the desire to transform each space into a unique work of art.',
      storyP2: 'Specializing in luxury interior design, we have developed a holistic approach that combines timeless elegance with contemporary innovation, creating interiors that transcend current trends.',
      storyP3: 'Our philosophy is based on the idea that each client is unique, and their home must reflect their personality, lifestyle and aspirations.',
      yearsExperience: 'Years of experience',
      completedProjects: 'Completed projects',
      happyClients: 'Happy clients',
      teamDescription: 'Experienced professionals dedicated to excellence in design',
      philosophyTitle: 'Our Philosophy',
      excellence: 'Excellence',
      excellenceDesc: 'Our high standards are reflected in every detail of the projects',
      personalization: 'Personalization',
      personalizationDesc: 'Each project is unique, perfectly adapted to the client\'s needs',
      exclusivity: 'Exclusivity',
      exclusivityDesc: 'Access to premium furniture and exclusive art pieces',
      startProject: 'Start your project'
    },
    services: {
      heroTitle: 'Premium',
      heroHighlight: 'Services',
      heroDescription: 'Our experience begins where your dream takes shape. Each project is treated with the attention and elegance it deserves, through complete service packages designed to accompany you every step — from the first sketches to the last decor detail.',
      heroDescription2: 'Everything is personalized: your pace, your style, your story. The result? A space that not only looks good but makes you feel at home.',
      completeDesignTitle: 'Complete Interior Design',
      completeDesignDesc: 'Our premium service for complete space transformation, from concept to turnkey.',
      consultancyTitle: 'Design Consultancy',
      consultancyDesc: 'Perfect for clients who want to implement the project through their own resources.',
      furnitureTitle: 'Premium Furniture Acquisition',
      furnitureDesc: 'Exclusive service for acquiring luxury furniture and accessories from our selected partners.',
      mostPopular: 'Most popular',
      requestQuote: 'Request quote',
      feature1: 'Concept and detailed plans',
      feature2: 'Premium furniture and decorations',
      feature3: 'Complete execution supervision',
      feature4: '2-year warranty for all work',
      feature5: 'Luxury materials and finishes',
      feature6: 'Post-completion consultancy',
      processTitle: 'Our',
      processHighlight: 'Work Process',
      processDescription: 'A structured and transparent process for exceptional results',
      step1Title: 'Initial Consultation',
      step1Desc: 'Home meeting to analyze the space and understand your needs',
      step2Title: 'Concept Development',
      step2Desc: 'Creating the design concept and presenting the detailed proposal',
      step3Title: 'Detailed Planning',
      step3Desc: 'Technical plans, materials list and implementation schedule',
      step4Title: 'Implementation',
      step4Desc: 'Project execution with constant supervision from our team',
      duration: 'Duration',
      guaranteesTitle: 'Our',
      guaranteesHighlight: 'Guarantees',
      qualityGuarantee: 'Quality Guarantee',
      qualityDesc: '2 years complete warranty for all work and materials used',
      budgetGuarantee: 'Budget Compliance',
      budgetDesc: 'Fixed price set from the start, no hidden or additional costs',
      deliveryGuarantee: 'On-Time Delivery',
      deliveryDesc: 'Adherence to established schedule or compensation for delays',
      ctaTitle: 'Ready to Start Your Project?',
      ctaDescription: 'The initial consultation is free and without obligation. Discover how we can transform your space.',
      scheduleFree: 'Schedule free consultation'
    },
    portfolio: {
      heroTitle: 'Premium Portfolio',
      heroDescription: 'Our collection of exclusive projects that redefine the standards of elegance and refinement',
      all: 'All',
      residential: 'Residential',
      commercial: 'Commercial',
      penthouse: 'Penthouse',
      villa: 'Villa',
      viewDetails: 'View details',
      processTitle: 'Our Process',
      processDescription: 'Each project follows a rigorous process from concept to completion',
      consultation: 'Consultation',
      consultationDesc: 'Detailed analysis of your needs and dreams',
      concept: 'Concept',
      conceptDesc: 'Development of a unique and personalized vision',
      execution: 'Execution',
      executionDesc: 'Precise implementation with premium materials',
      finalization: 'Finalization',
      finalizationDesc: 'Delivery of a perfect and functional space',
      startProject: 'Start your project'
    },
    contact: {
      heroTitle: 'Let\'s Start',
      heroHighlight: 'Together',
      heroDescription: 'The initial consultation is free and without obligation. Contact us to discuss your dream',
      formTitle: 'Schedule Your',
      formHighlight: 'Free Consultation',
      fullName: 'Full name',
      namePlaceholder: 'Your name',
      email: 'Email',
      emailPlaceholder: 'email@example.com',
      phone: 'Phone',
      phonePlaceholder: '+40 732 456 789',
      projectType: 'Project type',
      selectProject: 'Select project type',
      projectDetails: 'Project details',
      detailsPlaceholder: 'Tell us more about your vision...',
      scheduleCta: 'Schedule Free Consultation',
      nextSteps: 'What happens after submitting the form?',
      step1: 'We contact you within 24 hours',
      step2: 'We schedule the consultation at the right time',
      step3: 'You receive a personalized proposal',
      phoneTitle: 'Phone',
      emailTitle: 'Email',
      officeTitle: 'Office',
      scheduleTitle: 'Schedule',
      callNow: 'Call now',
      sendEmail: 'Send email',
      viewOnMap: 'View on map',
      scheduleVisit: 'Schedule visit',
      uniqueExperience: 'A Unique Experience Awaits You',
      personalizedConsultancy: 'Personalized consultancy',
      freeParking: 'Free parking available',
      scheduleOfficeVisit: 'Schedule a visit to our office',
      openInMaps: 'Open in Google Maps',
      faqTitle: 'Frequently Asked',
      faqHighlight: 'Questions',
      faq1Q: 'How long does a project take?',
      faq1A: 'Between 4-12 weeks, depending on the complexity of the project and the area of the space.',
      faq2Q: 'Do you offer a warranty?',
      faq2A: 'Yes, we offer a 2-year complete warranty for all work and materials used.',
      faq3Q: 'Do you work nationwide?',
      faq3A: 'Yes, we accept projects throughout the country for areas of minimum 150sqm.',
      faq4Q: 'What is the minimum budget?',
      faq4A: 'The minimum budget for a complete project is €25,000, including furniture and execution.',
      viewAllFaq: 'View all frequently asked questions',
      successTitle: 'Message sent successfully!',
      successDescription: 'We will contact you within 24 hours to schedule the consultation.'
    },
    blog: {
      heroTitle: 'Design',
      heroHighlight: 'Blog',
      heroDescription: 'Inspiration, tips and trends in interior design from Interior Design Bucharest experts',
      all: 'All',
      trends: 'Trends',
      tips: 'Tips',
      design: 'Design',
      materials: 'Materials',
      readMore: 'Read more',
      readTime: 'min read',
      newsletterTitle: 'Stay up to date with the news',
      newsletterDescription: 'Subscribe to our newsletter to receive the latest articles and design tips.',
      emailPlaceholder: 'Your email address',
      subscribe: 'Subscribe'
    },
    shop: {
      heroTitle: 'Premium resources for designers and architects',
      heroDescription: 'Templates, ebooks and CAD files that optimize your time, clarify your process and elevate your presentations to a professional level.',
      enterShop: '👉 Enter Shop',
      categories: 'Categories',
      allProducts: 'All products',
      ebooks: 'Ebooks',
      templates: 'Templates',
      cadFiles: 'CAD Files',
      packages: 'Complete packages',
      viewProduct: 'View product',
      whyWorksTitle: 'Why do these resources work?',
      benefit1: 'Helps you save hours in the work process',
      benefit2: 'Present projects in a professional and convincing way',
      benefit3: 'Helps you clearly organize the entire client flow',
      benefit4: 'Premium documents inspired by international studios',
      benefit5: 'Better results and a premium experience for the client',
      testimonial1: 'The documents are beautiful and intuitive. They completely changed the way I present projects.',
      testimonial2: 'I immediately felt how a premium agency looks. The templates are gold.',
      ctaTitle: 'Find the resources that streamline your work',
      ctaDescription: 'Premium documents for architects and designers who want more: order, professionalism, efficiency.',
      buyNow: '👉 Buy now'
    }
  },
  es: {
    nav: {
      about: 'Sobre Nosotros',
      portfolio: 'Portafolio',
      services: 'Servicios',
      blog: 'Blog',
      shop: 'Tienda',
      contact: 'Contacto',
      callNow: 'Llamar Ahora'
    },
    home: {
      heroTitle: 'Diseño Interior Bucarest',
      heroSubtitle: 'Transformamos espacios en obras de arte a través de la elegancia, el refinamiento y la atención al detalle',
      heroCta: 'Programa una consulta gratuita',
      aboutTitle: 'Excelencia en',
      aboutHighlight: 'Diseño Interior',
      aboutDescription: 'Con más de 13 años de experiencia creando espacios exclusivos, Jubilee Luxury Design combina arte, funcionalidad y elegancia para crear interiores que superan las expectativas.',
      feature1: 'Diseño personalizado y exclusivo',
      feature2: 'Materiales premium y mobiliario de lujo',
      feature3: 'Servicios completos llave en mano',
      readStory: 'Lee nuestra historia',
      projectsTitle: 'Proyectos',
      projectsHighlight: 'Exclusivos',
      projectsDescription: 'Cada proyecto es una historia única de elegancia y refinamiento, creada especialmente para nuestros clientes exigentes',
      viewPortfolio: 'Ver portafolio completo',
      ctaTitle: '¿Listo para transformar tu espacio?',
      residential: 'Residencial',
      commercial: 'Comercial',
      penthouse: 'Penthouse Exclusivo',
      villa: 'Villa Contemporánea',
      showroom: 'Showroom Premium'
    },
    footer: {
      inspirationTitle: 'Inspiración y',
      inspirationHighlight: 'Tendencias',
      inspirationDescription: 'Recibe mensualmente ideas exclusivas de diseño interior, tendencias y consejos de los expertos de Jubilee Luxury Design',
      emailPlaceholder: 'Tu correo electrónico',
      subscribe: 'Suscribirse',
      brandDescription: 'Durante más de 13 años, hemos creado espacios exclusivos que combinan elegancia con funcionalidad, ofreciendo servicios completos de diseño interior de lujo para clientes exigentes.',
      services: 'Servicios',
      aboutUs: 'Sobre Nosotros',
      resources: 'Recursos',
      completeDesign: 'Diseño Interior Completo',
      designConsultancy: 'Consultoría de Diseño',
      premiumFurniture: 'Mobiliario Premium',
      commercialDesign: 'Diseño Comercial',
      ourStory: 'Nuestra Historia',
      portfolio: 'Portafolio',
      testimonials: 'Testimonios',
      designBlog: 'Blog de Diseño',
      styleGuide: 'Guía de Estilos',
      allRights: 'Todos los derechos reservados.',
      privacyPolicy: 'Política de Privacidad',
      termsConditions: 'Términos y Condiciones',
      cookiesPolicy: 'Política de Cookies'
    },
    about: {
      heroTitle: 'La Historia de',
      heroHighlight: 'Jubilee Luxury Design',
      heroDescription: 'Durante más de 13 años, hemos creado espacios exclusivos que reflejan la personalidad y los sueños de nuestros clientes',
      storyTitle: 'Una Visión Nacida de la Pasión',
      storyP1: 'Jubilee Luxury Design nació en 2012 de una pasión por la belleza, la funcionalidad y el deseo de transformar cada espacio en una obra de arte única.',
      storyP2: 'Especializándonos en diseño interior de lujo, hemos desarrollado un enfoque holístico que combina la elegancia atemporal con la innovación contemporánea, creando interiores que trascienden las tendencias actuales.',
      storyP3: 'Nuestra filosofía se basa en la idea de que cada cliente es único, y su hogar debe reflejar su personalidad, estilo de vida y aspiraciones.',
      yearsExperience: 'Años de experiencia',
      completedProjects: 'Proyectos completados',
      happyClients: 'Clientes satisfechos',
      teamDescription: 'Profesionales experimentados dedicados a la excelencia en diseño',
      philosophyTitle: 'Nuestra Filosofía',
      excellence: 'Excelencia',
      excellenceDesc: 'Nuestros altos estándares se reflejan en cada detalle de los proyectos',
      personalization: 'Personalización',
      personalizationDesc: 'Cada proyecto es único, perfectamente adaptado a las necesidades del cliente',
      exclusivity: 'Exclusividad',
      exclusivityDesc: 'Acceso a mobiliario premium y piezas de arte exclusivas',
      startProject: 'Inicia tu proyecto'
    },
    services: {
      heroTitle: 'Servicios',
      heroHighlight: 'Premium',
      heroDescription: 'Nuestra experiencia comienza donde tu sueño toma forma. Cada proyecto es tratado con la atención y elegancia que merece, a través de paquetes completos de servicios diseñados para acompañarte en cada paso — desde los primeros bocetos hasta el último detalle de decoración.',
      heroDescription2: 'Todo es personalizado: tu ritmo, tu estilo, tu historia. ¿El resultado? Un espacio que no solo luce bien, sino que te hace sentir en casa.',
      completeDesignTitle: 'Diseño Interior Completo',
      completeDesignDesc: 'Nuestro servicio premium para la transformación completa del espacio, desde el concepto hasta llave en mano.',
      consultancyTitle: 'Consultoría de Diseño',
      consultancyDesc: 'Perfecto para clientes que desean implementar el proyecto con sus propios recursos.',
      furnitureTitle: 'Adquisición de Mobiliario Premium',
      furnitureDesc: 'Servicio exclusivo de adquisición de mobiliario y accesorios de lujo de nuestros socios seleccionados.',
      mostPopular: 'Más popular',
      requestQuote: 'Solicitar presupuesto',
      feature1: 'Concepto y planos detallados',
      feature2: 'Mobiliario y decoraciones premium',
      feature3: 'Supervisión completa de ejecución',
      feature4: 'Garantía de 2 años para todos los trabajos',
      feature5: 'Materiales y acabados de lujo',
      feature6: 'Consultoría post-finalización',
      processTitle: 'Nuestro Proceso de',
      processHighlight: 'Trabajo',
      processDescription: 'Un proceso estructurado y transparente para resultados excepcionales',
      step1Title: 'Consulta Inicial',
      step1Desc: 'Reunión a domicilio para analizar el espacio y entender tus necesidades',
      step2Title: 'Desarrollo del Concepto',
      step2Desc: 'Creación del concepto de diseño y presentación de la propuesta detallada',
      step3Title: 'Planificación Detallada',
      step3Desc: 'Planos técnicos, lista de materiales y cronograma de implementación',
      step4Title: 'Implementación',
      step4Desc: 'Ejecución del proyecto con supervisión constante de nuestro equipo',
      duration: 'Duración',
      guaranteesTitle: 'Nuestras',
      guaranteesHighlight: 'Garantías',
      qualityGuarantee: 'Garantía de Calidad',
      qualityDesc: '2 años de garantía completa para todos los trabajos y materiales utilizados',
      budgetGuarantee: 'Cumplimiento del Presupuesto',
      budgetDesc: 'Precio fijo establecido desde el inicio, sin costos ocultos o adicionales',
      deliveryGuarantee: 'Entrega a Tiempo',
      deliveryDesc: 'Cumplimiento del programa establecido o compensación por retrasos',
      ctaTitle: '¿Listo para Iniciar tu Proyecto?',
      ctaDescription: 'La consulta inicial es gratuita y sin compromiso. Descubre cómo podemos transformar tu espacio.',
      scheduleFree: 'Programa consulta gratuita'
    },
    portfolio: {
      heroTitle: 'Portafolio Premium',
      heroDescription: 'Nuestra colección de proyectos exclusivos que redefinen los estándares de elegancia y refinamiento',
      all: 'Todos',
      residential: 'Residencial',
      commercial: 'Comercial',
      penthouse: 'Penthouse',
      villa: 'Villa',
      viewDetails: 'Ver detalles',
      processTitle: 'Nuestro Proceso',
      processDescription: 'Cada proyecto sigue un proceso riguroso desde el concepto hasta la finalización',
      consultation: 'Consulta',
      consultationDesc: 'Análisis detallado de tus necesidades y sueños',
      concept: 'Concepto',
      conceptDesc: 'Desarrollo de una visión única y personalizada',
      execution: 'Ejecución',
      executionDesc: 'Implementación precisa con materiales premium',
      finalization: 'Finalización',
      finalizationDesc: 'Entrega de un espacio perfecto y funcional',
      startProject: 'Inicia tu proyecto'
    },
    contact: {
      heroTitle: 'Comencemos',
      heroHighlight: 'Juntos',
      heroDescription: 'La consulta inicial es gratuita y sin compromiso. Contáctanos para hablar sobre tu sueño',
      formTitle: 'Programa tu Consulta',
      formHighlight: 'Gratuita',
      fullName: 'Nombre completo',
      namePlaceholder: 'Tu nombre',
      email: 'Correo electrónico',
      emailPlaceholder: 'email@ejemplo.com',
      phone: 'Teléfono',
      phonePlaceholder: '+40 732 456 789',
      projectType: 'Tipo de proyecto',
      selectProject: 'Selecciona el tipo de proyecto',
      projectDetails: 'Detalles del proyecto',
      detailsPlaceholder: 'Cuéntanos más sobre tu visión...',
      scheduleCta: 'Programa Consulta Gratuita',
      nextSteps: '¿Qué sucede después de enviar el formulario?',
      step1: 'Te contactamos en máximo 24 horas',
      step2: 'Programamos la consulta en el momento adecuado',
      step3: 'Recibes una propuesta personalizada',
      phoneTitle: 'Teléfono',
      emailTitle: 'Correo',
      officeTitle: 'Oficina',
      scheduleTitle: 'Horario',
      callNow: 'Llamar ahora',
      sendEmail: 'Enviar correo',
      viewOnMap: 'Ver en mapa',
      scheduleVisit: 'Programar visita',
      uniqueExperience: 'Una Experiencia Única te Espera',
      personalizedConsultancy: 'Consultoría personalizada',
      freeParking: 'Estacionamiento gratuito disponible',
      scheduleOfficeVisit: 'Programa una visita a nuestra oficina',
      openInMaps: 'Abrir en Google Maps',
      faqTitle: 'Preguntas',
      faqHighlight: 'Frecuentes',
      faq1Q: '¿Cuánto tiempo dura un proyecto?',
      faq1A: 'Entre 4-12 semanas, dependiendo de la complejidad del proyecto y el área del espacio.',
      faq2Q: '¿Ofrecen garantía?',
      faq2A: 'Sí, ofrecemos 2 años de garantía completa para todos los trabajos y materiales utilizados.',
      faq3Q: '¿Trabajan en todo el país?',
      faq3A: 'Sí, aceptamos proyectos en todo el país para áreas de mínimo 150m².',
      faq4Q: '¿Cuál es el presupuesto mínimo?',
      faq4A: 'El presupuesto mínimo para un proyecto completo es de €25,000, incluyendo mobiliario y ejecución.',
      viewAllFaq: 'Ver todas las preguntas frecuentes',
      successTitle: '¡Mensaje enviado con éxito!',
      successDescription: 'Te contactaremos en máximo 24 horas para programar la consulta.'
    },
    blog: {
      heroTitle: 'Blog de',
      heroHighlight: 'Diseño',
      heroDescription: 'Inspiración, consejos y tendencias en diseño interior de los expertos de Diseño Interior Bucarest',
      all: 'Todos',
      trends: 'Tendencias',
      tips: 'Consejos',
      design: 'Diseño',
      materials: 'Materiales',
      readMore: 'Leer más',
      readTime: 'min lectura',
      newsletterTitle: 'Mantente al día con las novedades',
      newsletterDescription: 'Suscríbete a nuestro boletín para recibir los últimos artículos y consejos de diseño.',
      emailPlaceholder: 'Tu correo electrónico',
      subscribe: 'Suscribirse'
    },
    shop: {
      heroTitle: 'Recursos premium para diseñadores y arquitectos',
      heroDescription: 'Plantillas, ebooks y archivos CAD que optimizan tu tiempo, clarifican tu proceso y elevan tus presentaciones a nivel profesional.',
      enterShop: '👉 Entrar a la Tienda',
      categories: 'Categorías',
      allProducts: 'Todos los productos',
      ebooks: 'Ebooks',
      templates: 'Plantillas',
      cadFiles: 'Archivos CAD',
      packages: 'Paquetes completos',
      viewProduct: 'Ver producto',
      whyWorksTitle: '¿Por qué funcionan estos recursos?',
      benefit1: 'Te ayuda a ahorrar horas en el proceso de trabajo',
      benefit2: 'Presenta proyectos de manera profesional y convincente',
      benefit3: 'Te ayuda a organizar claramente todo el flujo con el cliente',
      benefit4: 'Documentos premium inspirados en estudios internacionales',
      benefit5: 'Mejores resultados y una experiencia premium para el cliente',
      testimonial1: 'Los documentos son hermosos e intuitivos. Cambiaron completamente la forma en que presento proyectos.',
      testimonial2: 'Inmediatamente sentí cómo se ve una agencia premium. Las plantillas son oro.',
      ctaTitle: 'Encuentra los recursos que optimizan tu trabajo',
      ctaDescription: 'Documentos premium para arquitectos y diseñadores que quieren más: orden, profesionalismo, eficiencia.',
      buyNow: '👉 Comprar ahora'
    }
  }
};

export default LanguageContext;
